---

apiVersion: kustomize.toolkit.fluxcd.io/v1

kind: Kustomization

metadata:

  labels:

    kustomize.toolkit.fluxcd.io/name: k8tz

    kustomize.toolkit.fluxcd.io/namespace: flux-system

  name: k8tz

  namespace: flux-system

spec:

  interval: 1m0s

  path: ./nortura-infra/dev-k8tz

  prune: true

  sourceRef:

    kind: GitRepository

    name: flux-system